services:
  # 1. Database PostgreSQL (Manteniamo i tuoi nomi e il tuo volume)
  postgres:
    image: postgres:16-alpine
    container_name: order-postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Kafka (Configurazione "Kraft" senza Zookeeper, pi√π moderna)
  #kafka:
  #  image: apache/kafka:latest
  #  container_name: kafka
  #  ports:
  #    - "9092:9092"
  #  environment:
  #    KAFKA_NODE_ID: 1
  #    KAFKA_PROCESS_ROLES: broker,controller
  #    KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
  #    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
  #    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 3. Order Service
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      # Usiamo il nome del servizio 'postgres' come hostname
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_service_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres
      #- kafka

  # 4. Inventory Service
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-service
    # Port 8081 se vuoi esporre API anche qui
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    #depends_on:
      #- kafka

volumes:
  postgres_data: